puduvai_pention/UserAuth/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.signin, name='account_login'),
    path('logout', views.logout_view, name='account_logout'),
]

puduvai_pention/puduvai_pention/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('django.contrib.auth.urls')),
    path('', include('UserAuth.urls')),
    path('',include('pension_candidates.urls'))  
]

puduvai_pention/Pension_candidates/models.py
from datetime import datetime
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import datetime_safe


class TypesOfPension(models.Model):
    type = models.CharField(max_length=10, primary_key=True)
    full_form = models.CharField(max_length=256, null=True, blank=True)
    details = models.TextField(blank=True, null=True)

    def __str__(self) -> str:
        return f'{self.type} | {self.full_form}'
    


class Employee(models.Model):
    BANK_CHOICE = (
        ('IOB_M','Indian Overseas Bank - Town Branch'),
        ('IOB_O', 'Indian Overseas Bank - Other Branch'),
        ('SBI_M','State Bank of India - Main Branch'),
        ('SBI_O', 'State Bank of India - Other Branch'),
    )
    AGE_CHOICES=(
        ('below_80','Below 80 years'),
        ('80','80 years'),
        ('85','85 years'),
        ('90','90 years'),
    )

    bank = models.CharField(max_length=7, choices=BANK_CHOICE, verbose_name=_('Select Bank Branch'))
    pk_ppo = models.CharField(max_length=256, primary_key=True)
    monthly_date = models.CharField(max_length=7, verbose_name=_('Date'))
    ppo = models.CharField(max_length=200,null=True,blank=True)
    acc = models.PositiveIntegerField(null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    age = models.CharField(max_length=200,choices = AGE_CHOICES,blank=True)
    designation = models.CharField(max_length=256, null=True, blank=True)
    types = models.ForeignKey(TypesOfPension, on_delete=models.RESTRICT, null=True)
    basic = models.PositiveIntegerField(null=True, blank=True)
    additional = models.PositiveIntegerField(null=True, blank=True)
    total1 = models.PositiveIntegerField(null=True, blank=True)
    comuted = models.PositiveIntegerField(null=True, blank=True, default=0)
    residuary = models.PositiveIntegerField(null=True, blank=True)
    dr = models.PositiveIntegerField(null=True, blank=True)
    fma = models.PositiveIntegerField(null=True, blank=True)
    emolume = models.PositiveIntegerField(null=True, blank=True)
    amount = models.PositiveIntegerField(null=True, blank=True)
    less = models.PositiveIntegerField(null=True, blank=True)
    Total2 = models.PositiveIntegerField(null=True, blank=True)
    remarks = models.CharField(max_length=200,null=True, blank=True)
    remarks_text = models.TextField(null=True, blank=True)
    remarks_date = models.CharField(null=True, max_length=10, verbose_name=_('Date for Remarks'))
    issued_at = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.remarks_text:
            formatted_date = self.remarks_date.strftime('%d-%m-%Y') if self.remarks_date is not None else ''
            self.remarks = self.remarks_text + (f" ({formatted_date})" if formatted_date else '')
        super().save(*args, **kwargs)


    def __str__(self):
        return f'{self.ppo} | {self.monthly_date}'

    @staticmethod
    def calculate_group_totals(group, prev_totals=None):
        fields = ['basic', 'additional', 'total1', 'comuted', 'residuary', 'dr', 'fma', 'emolume', 'amount', 'less', 'Total2']
        group_totals = {field: sum(getattr(item, field, 0) or 0 for item in group) for field in fields}

        if prev_totals is not None:
            print(type(prev_totals))
            group_totals = {j: group_totals[j] + prev_totals.get(j, 0) for j in group_totals}
        return group_totals

    

puduvai_pention/Pension_candidates/forms.py
from django import forms
from .models import Employee,TypesOfPension
from datetime import date


class EmployeeForm(forms.ModelForm):
    bank = forms.ChoiceField(
    choices=[('', '---------')] + list(Employee.BANK_CHOICE),
    widget=forms.Select(attrs={'class': 'form-control'}),
    label = 'Select bank Branch'
    )
    types = forms.ModelChoiceField(
        queryset=TypesOfPension.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        label = 'Types Of pension'
    )
    basic = forms.IntegerField(label='Revised Basic Pension')
    # additional = forms.IntegerField(label='Revised Additional Pension')
    comuted = forms.IntegerField(label='Less Commuted Value')
    issued_at = forms.DateField(widget=forms.SelectDateWidget(attrs={'class': 'form-control'}), required=False)
    age = forms.ChoiceField(
    choices=[('', '---------')]+list(Employee.AGE_CHOICES),
    widget=forms.Select(attrs={'class': 'form-control'}),
    label = 'Choose Age'
    )
    remarks_date = forms.DateField(required=False,widget=forms.DateInput(attrs={'type': 'date'}))
    
    
    def clean(self):
        cleaned_data = super().clean()
        age = cleaned_data.get('age')
        basic = cleaned_data.get('basic')
        additional = cleaned_data.get('additional')
        comuted = cleaned_data.get('comuted')
        issued_at = cleaned_data.get('issued_at')
        if issued_at:
         if issued_at > date.today():
            self.add_error('issued_at', 'Issued at date must be in the past')
        if age == 'below_80' and basic and not additional:
            additional = basic * 0 
            cleaned_data['additional'] = additional
        elif age == '80' and basic and not additional:
            additional = basic * 0.20
            cleaned_data['additional'] = additional
        elif age == '85' and basic and not additional:
            additional = basic * 0.30
            cleaned_data['additional'] = additional 
        elif age == '90' and basic and not additional:
            additional = basic * 0.40
            cleaned_data['additional'] = additional
        if basic and additional:
            cleaned_data['total1'] = basic + additional
            cleaned_data['dr'] = cleaned_data['total1'] * 0.38
        if cleaned_data.get('total1') and comuted:
            cleaned_data['residuary'] = cleaned_data['total1'] - comuted
        if cleaned_data.get('residuary') and cleaned_data.get('dr') and cleaned_data.get('fma'):
            cleaned_data['emolume'] = cleaned_data['residuary'] + cleaned_data['dr'] + cleaned_data['fma']
        if cleaned_data.get('emolume') and cleaned_data.get('amount') and cleaned_data.get('less'):
            cleaned_data['Total2'] = cleaned_data['emolume'] + cleaned_data['amount'] - cleaned_data['less']
        return cleaned_data
    
    class Meta:
        model = Employee
        fields = (
            'bank', 'monthly_date', 'ppo', 'acc', 'name', 'designation',
            'types', 'basic', 'additional', 'total1',
            'comuted', 'residuary', 'dr', 'fma', 'emolume',
            'amount', 'less', 'Total2', 'remarks_text','issued_at',
        )
        
        widgets = {
             'ppo': forms.TextInput(attrs={'class': 'form-control'}),
             'monthly_date': forms.TextInput(attrs={'type':'month'}),
             'residuary': forms.NumberInput(attrs={'disabled': 'disabled', 'placeholder': 'Total Pension + Less Commuted Value'}),
             'total1': forms.TextInput(attrs={'disabled': 'disabled', 'placeholder': 'Basic Pension + Additional Pension'}),
             'additional': forms.TextInput(attrs={'disabled': 'disabled', 'placeholder': 'Basic Pension * Selected Age'}),
             'dr': forms.TextInput(attrs={'disabled': 'disabled', 'placeholder': 'Total Pension * 0.38'}),
             'emolume': forms.TextInput(attrs={'disabled': 'disabled', 'placeholder': 'Residuary+DR+F.M.A.'}),
             'Total2': forms.TextInput(attrs={'disabled': 'disabled', 'placeholder': 'Final amount'}),

}

        labels = {
            'ppo': 'PPO No',
            'acc': 'Account Number',
            'monthly_date': 'Date',
            'name': 'Name',
            'designation': 'Designation',
            'types': 'Types of pension',
            'basic': 'Revised Basic Pension',
            'additional': 'Revised Additional Pension on 80 years above',
            'total1': 'Total Pension',
            'comuted': 'Less Commuted Value',
            'residuary': 'Residuary Pension',
            'dr': 'DR 38%',
            'fma': 'F.M.A',
            'emolume': 'Total Emolume nts(7th NPC)',
            'amount': 'Add Pension Amount',
            'less': 'Less Excess Amount',
            'Total2': 'Total',
            'remarks_text': 'Remarks',
            'remarks_date': 'Remarks with Date'
        }

puduvai_pention/templates/bank.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
{% include 'sidebar.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" > 
    <link rel="stylesheet" href="{% static 'css/bankoption.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/import.css' %}"> -->
    <title>Document</title>
</head>
<body>
    <div class="container">
        <h5 class="title">IMPORTING DATA</h5>
        <ul>
            <li class="dropdown">
                <a href="" data-toggle="dropdown">Choose Bank Option <i class="icon-arrow"></i></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'import' bank='IOB_M' %}">Indian Overseas Bank(Main Branch)</a></li>
                    <li><a href="{% url 'import' bank='IOB_O' %}">Indian Overseas Bank(Other Branch)</a></li>
                    <li><a href="{% url 'import' bank='SBI_M' %}">State Bank of India(Main Branch)</a></li>
                    <li><a href="{% url 'import' bank='SBI_O' %}">State Bank of India(Other Branch)</a></li>
                </ul>
            </li>
        </ul>

        <!-- <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="file-upload">
                <div class="file-select">
                    <div class="file-select-button" id="fileName">Choose File</div>
                    <div class="file-select-name" id="noFile">No file chosen...</div> 
                    <input type="file" name="file" id="file">
                </div>
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Import</button>
        </form> -->
    </div>

    <script src="{% static 'js/bank.js' %}"></script> 
    <script>
        $('#file').bind('change', function () {
            var filename = $("#file").val();
            if (/^\s*$/.test(filename)) {
                $(".file-upload").removeClass('active');
                $("#noFile").text("No file chosen..."); 
            } else {
                $(".file-upload").addClass('active');
                $("#noFile").text(filename.replace("C:\\fakepath\\", "")); 
            }
        });
    </script>
</body>
</html>

puduvai_pention/templates/base.html
<!DOCTYPE html>
{% load static %}
{% include 'sidebar.html'%}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Puduvai Pention {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" /> 
    <Link rel="stylesheet"href="{% static 'css/style.css'%}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.3.0/css/all.css">
    <link rel="stylesheet" href="{% static 'css/newsidebar.css' %}"> 
  <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'> 
  <script src="{% static 'js/script.js' %}"></script>
  </head>
  <body>
    {% if user.is_authenticate %}
    {% include 'sidebar.html' %}
    <div class="content">
        {% block content %}{% endblock %}
    </div>
    <footer class="footer">
      <div class="content text-center">
        <p>
          <strong> Puduvai Pention </strong>
          by
          <a href="https://jgthms.com"> Vignesh </a>
          . The source code is licensed under
          <a href="https://www.gnu.org/licenses/gpl-3.0.en.html"> GPLv3 </a>
        </p>
      </div>
    </div></div></div>
    </footer>
  </body>
</html>

puduvai_pention/templates/create.html
<html>
    {% load static %}
    {% include 'sidebar.html' %}
    {% load crispy_forms_tags %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
         <link rel="stylesheet" href="{% static 'css/sidebarbootstrap.css' %}"> 
        <!-- <script src="{% static 'js/jquery.min.js' %}"></script> -->
         <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" > 
    </head>
    <body>
        <div class="wrapper rounded bg-white ">
            <!-- <div class="wrapper rounded bg-white"> -->
            <div class="h3 text-center">ADD PENSIONER</div>
            {% if error %} <!-- warning handling --> 
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>Alert! </strong>: {{error}}.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
             <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 mt-md-0 mt-3" data-style="btn-success">
                        {{form.bank|as_crispy_field}}
                    </div>
                    <div class="col-md-6 mt-md-0 mt-3">
                        {{form.monthly_date|as_crispy_field}}
                    </div>
                </div>
                    <div class="row">
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.ppo|as_crispy_field}}
                        </div>
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.acc|as_crispy_field}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.age|as_crispy_field}}
                        </div>
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.name|as_crispy_field}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.designation|as_crispy_field}}
                        </div>
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.types|as_crispy_field}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.basic|as_crispy_field}}
                        </div>
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.additional|as_crispy_field}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.total1|as_crispy_field}}
                        </div>
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.comuted|as_crispy_field}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.residuary|as_crispy_field}}
                        </div>
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.dr|as_crispy_field}}
                        </div>
                    </div>
                        <div class="row">
                            <div class="col-md-6 mt-md-0 mt-3">
                                {{form.fma|as_crispy_field}}
                            </div>
                            <div class="col-md-6 mt-md-0 mt-3">
                                {{form.emolume|as_crispy_field}}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 mt-md-0 mt-3">
                                {{form.amount|as_crispy_field}}
                            </div>
                            <div class="col-md-6 mt-md-0 mt-3">
                                {{form.less|as_crispy_field}}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 mt-md-0 mt-3">
                                {{form.Total2|as_crispy_field}}
                            </div>
                            <div class="col-md-6 mt-md-0 mt-3">
                                {{form.remarks_text|as_crispy_field}}
                                {{form.remarks_date|as_crispy_field}}
                            </div>
                        </div>
                        <div class="row">
                        </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <script>
                const ageField = document.querySelector('#id_age');
                const basicField = document.querySelector('#id_basic');
                const additionalField = document.querySelector('#id_additional');
                const comutedField = document.querySelector('#id_comuted');
                const total1Field = document.querySelector('#id_total1');
                const residuaryField = document.querySelector('#id_residuary');
                const drField = document.querySelector('#id_dr');
                const fmaField = document.querySelector('#id_fma');
                const emolumeField = document.querySelector('#id_emolume');
                const amountField = document.querySelector('#id_amount');
                const lessField = document.querySelector('#id_less');
                const Total2Field = document.querySelector('#id_Total2');
            
                ageField.addEventListener('change', updateAdditionalFormula);
                basicField.addEventListener('input', updateTotal);
                additionalField.addEventListener('input', updateTotal);
                comutedField.addEventListener('input', updateTotal);
                emolumeField.addEventListener('input', updateTotal2);
                amountField.addEventListener('input', updateTotal2);
                lessField.addEventListener('input', updateTotal2);
            
                function updateTotal() {
                    const basic = parseFloat(basicField.value) || 0;
                    const additional = parseFloat(additionalField.value) || 0;
                    const comuted = parseFloat(comutedField.value) || 0;
                    const total1 = basic + additional;
                    const residuary = total1 - comuted;
                    const dr = total1 * 0.38;
                    const fma = parseFloat(fmaField.value) || 0;
                    const emolume = residuary + dr + fma;
                    total1Field.value = total1.toFixed(2);
                    residuaryField.value = residuary.toFixed(2);
                    drField.value = dr.toFixed(2);
                    fmaField.value = fma.toFixed(2);
                    emolumeField.value = emolume.toFixed(2);
                }
            
                function updateAdditionalFormula() {
                    const age = ageField.value;
                    if (age === 'below_80') {
                        additionalField.value = basicField.value;
                    } else if (age === '80') {
                        additionalField.value = basicField.value * 0.20 || '';
                    } else if (age === '85') {
                        additionalField.value = basicField.value * 0.30 || '';
                    } else if (age === '90') {
                        additionalField.value = basicField.value * 0.40 || '';
                    }
                    updateTotal1();
                    updateTotal2();
                    
                }
            
                function updateTotal2() {
                    const emolume = parseFloat(emolumeField.value) || 0;
                    const amount = parseFloat(amountField.value) || 0;
                    const less = parseFloat(lessField.value) || 0;
                    const Total2 = emolume + amount - less;
                    Total2Field.value = Total2.toFixed(2);
                }
            
                function updateTotal1() {
                    const basic = parseFloat(basicField.value) || 0;
                    const additional = parseFloat(additionalField.value) || 0;
                    const total1 = basic + additional;
                    const residuary = total1 - parseFloat(comutedField.value) || 0;
                    total1Field.value = total1.toFixed(2);
                    residuaryField.value = residuary.toFixed(2);
                    updateTotal();
                }
                     var closeBtn = document.querySelector('.alert .close');
                     closeBtn.addEventListener('click', function() {
                     var alertDiv = closeBtn.parentElement;
          alertDiv.remove();
        });
            </script>
            
        </div> 
    </body>
</html>

puduvai_pention/templates/delete.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <head>
           <link rel="stylesheet" href="{% static 'css/sidebarbootstrap.css' %}"> 
          <!-- <script src="{% static 'js/jquery.min.js' %}"></script> -->
           <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" > 
      </head>
    <title>Delete</title>
</head>
<body>
  <div class="wrapper rounded bg-white ">
  <p>Are you sure you want to delete {{ employee.ppo }}?</p>
  <form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <button onclick="location.href='{% url 'edit' month=month bank=bank %}'" type="button" class="btn btn-primary">Cancel</button>
  </form>
</div>
</body>
</html>

puduvai_pention/templates/update.html
<html>
    {% load static %}
    {% include 'sidebar.html' %}
    {% load crispy_forms_tags %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <head>
         <link rel="stylesheet" href="{% static 'css/sidebarbootstrap.css' %}"> 
        <!-- <script src="{% static 'js/jquery.min.js' %}"></script> -->
         <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" > 
    </head>
    <body>
        <div class="wrapper rounded bg-white ">
            <!-- <div class="wrapper rounded bg-white"> -->
            <div class="h3 text-center">UPDATE PENSIONER</div>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6 mt-md-0 mt-3" data-style="btn-success">
                        {{form.bank|as_crispy_field}}
                    </div>
                    <div class="col-md-6 mt-md-0 mt-3">
                        {{form.monthly_date|as_crispy_field}}
                    </div>
                </div>
                    <div class="row">
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.ppo|as_crispy_field}}
                        </div>
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.acc|as_crispy_field}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.age|as_crispy_field}}
                        </div>
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.name|as_crispy_field}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.designation|as_crispy_field}}
                        </div>
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.types|as_crispy_field}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.basic|as_crispy_field}}
                        </div>
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.additional|as_crispy_field}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.total1|as_crispy_field}}
                        </div>
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.comuted|as_crispy_field}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.residuary|as_crispy_field}}
                        </div>
                        <div class="col-md-6 mt-md-0 mt-3">
                            {{form.dr|as_crispy_field}}
                        </div>
                    </div>
                        <div class="row">
                            <div class="col-md-6 mt-md-0 mt-3">
                                {{form.fma|as_crispy_field}}
                            </div>
                            <div class="col-md-6 mt-md-0 mt-3">
                                {{form.emolume|as_crispy_field}}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 mt-md-0 mt-3">
                                {{form.amount|as_crispy_field}}
                            </div>
                            <div class="col-md-6 mt-md-0 mt-3">
                                {{form.less|as_crispy_field}}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 mt-md-0 mt-3">
                                {{form.Total2|as_crispy_field}}
                            </div>
                            <div class="col-md-6 mt-md-0 mt-3">
                                {{form.remarks_text|as_crispy_field}}
                                {{form.remarks_date|as_crispy_field}}
                            </div>
                        </div>
                        <div class="row">
                        </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <script>
                const ageField = document.querySelector('#id_age');
                const basicField = document.querySelector('#id_basic');
                const additionalField = document.querySelector('#id_additional');
                const comutedField = document.querySelector('#id_comuted');
                const total1Field = document.querySelector('#id_total1');
                const residuaryField = document.querySelector('#id_residuary');
                const drField = document.querySelector('#id_dr');
                const fmaField = document.querySelector('#id_fma');
                const emolumeField = document.querySelector('#id_emolume');
                const amountField = document.querySelector('#id_amount');
                const lessField = document.querySelector('#id_less');
                const Total2Field = document.querySelector('#id_Total2');
            
                ageField.addEventListener('change', updateAdditionalFormula);
                basicField.addEventListener('input', updateTotal);
                additionalField.addEventListener('input', updateTotal);
                comutedField.addEventListener('input', updateTotal);
                emolumeField.addEventListener('input', updateTotal2);
                amountField.addEventListener('input', updateTotal2);
                lessField.addEventListener('input', updateTotal2);
            
                function updateTotal() {
                    const basic = parseFloat(basicField.value) || 0;
                    const additional = parseFloat(additionalField.value) || 0;
                    const comuted = parseFloat(comutedField.value) || 0;
                    const total1 = basic + additional;
                    const residuary = total1 - comuted;
                    const dr = total1 * 0.38;
                    const fma = parseFloat(fmaField.value) || 0;
                    const emolume = residuary + dr + fma;
                    total1Field.value = total1.toFixed(2);
                    residuaryField.value = residuary.toFixed(2);
                    drField.value = dr.toFixed(2);
                    fmaField.value = fma.toFixed(2);
                    emolumeField.value = emolume.toFixed(2);
                }
            
                function updateAdditionalFormula() {
                    const age = ageField.value;
                    if (age === 'below_80') {
                        additionalField.value = basicField.value;
                    } else if (age === '80') {
                        additionalField.value = basicField.value * 0.20 || '';
                    } else if (age === '85') {
                        additionalField.value = basicField.value * 0.30 || '';
                    } else if (age === '90') {
                        additionalField.value = basicField.value * 0.40 || '';
                    }
                    updateTotal1();
                    updateTotal2();
                    
                }
            
                function updateTotal2() {
                    const emolume = parseFloat(emolumeField.value) || 0;
                    const amount = parseFloat(amountField.value) || 0;
                    const less = parseFloat(lessField.value) || 0;
                    const Total2 = emolume + amount - less;
                    Total2Field.value = Total2.toFixed(2);
                }
            
                function updateTotal1() {
                    const basic = parseFloat(basicField.value) || 0;
                    const additional = parseFloat(additionalField.value) || 0;
                    const total1 = basic + additional;
                    const residuary = total1 - parseFloat(comutedField.value) || 0;
                    total1Field.value = total1.toFixed(2);
                    residuaryField.value = residuary.toFixed(2);
                    updateTotal();
                }
            </script>
            
        </div> 
    </body>
</html>